#!/usr/bin/env bash

set -uo pipefail

APP_NAME="codingagentconfig"
WORKSPACE_BASE_DEFAULT="/home/node/project"

TOOLS=(
  "codex|@openai/codex|npm"
  "claude code|@anthropic-ai/claude-code|npm"
  "claudecodeui|@siteboon/claude-code-ui|npm"
  "ccman|ccman|npm"
  "cc-connect|cc-connect|source"
)

declare -a TOOL_CURRENT=()
declare -a TOOL_LATEST=()
declare -a TOOL_STATUS=()
declare -a TOOL_CAN_UPDATE=()

pause() {
  echo
  read -r -p "Press Enter to continue..."
}

trim() {
  local s="$1"
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  printf '%s' "${s}"
}

normalize_semver() {
  local v="${1:-}"
  v="$(trim "${v}")"
  v="${v#v}"
  printf '%s' "${v}"
}

extract_semver() {
  local raw="${1:-}"
  printf '%s' "${raw}" | grep -Eo 'v?[0-9]+\.[0-9]+\.[0-9]+' | head -n 1 | sed 's/^v//'
}

have_cmd() {
  command -v "$1" >/dev/null 2>&1
}

HC_PASS=0
HC_FAIL=0
HC_SKIP=0

health_pass() {
  HC_PASS=$((HC_PASS + 1))
  echo "PASS: $*"
}

health_fail() {
  HC_FAIL=$((HC_FAIL + 1))
  echo "FAIL: $*"
}

health_skip() {
  HC_SKIP=$((HC_SKIP + 1))
  echo "SKIP: $*"
}

health_check() {
  local name="$1"
  local cmd="$2"
  if bash -lc "${cmd}" >/dev/null 2>&1; then
    health_pass "${name}"
  else
    health_fail "${name}"
  fi
}

toml_escape() {
  local s="${1:-}"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '%s' "${s}"
}

prompt_yes_no() {
  local prompt="$1"
  local default="${2:-N}"
  local answer=""
  read -r -p "${prompt} " answer
  answer="$(trim "${answer}")"
  if [[ -z "${answer}" ]]; then
    answer="${default}"
  fi
  [[ "${answer}" =~ ^[Yy]$ ]]
}

cc_connect_config_path() {
  printf '%s' "${CC_CONNECT_CONFIG_PATH:-/home/node/.cc-connect/config.toml}"
}

ensure_cc_connect_config() {
  local cfg="$1"
  local dir
  dir="$(dirname "${cfg}")"
  mkdir -p "${dir}" || return 1
  if [[ ! -f "${cfg}" ]]; then
    cat >"${cfg}" <<'EOF'
# cc-connect config generated by codingagentconfig
# Add more project blocks as needed.
EOF
  fi
}

cc_project_exists() {
  local cfg="$1"
  local name="$2"
  grep -Eq "^[[:space:]]*name[[:space:]]*=[[:space:]]*\"${name}\"[[:space:]]*$" "${cfg}"
}

port_is_listening() {
  local port="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -ltn 2>/dev/null | awk '{print $4}' | grep -Eq "[:.]${port}$"
    return $?
  fi
  if command -v netstat >/dev/null 2>&1; then
    netstat -ltn 2>/dev/null | awk '{print $4}' | grep -Eq "[:.]${port}$"
    return $?
  fi
  if command -v python3 >/dev/null 2>&1; then
    python3 - "${port}" <<'PY'
import socket
import sys

port = int(sys.argv[1])
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.settimeout(0.5)
try:
    rc = sock.connect_ex(("127.0.0.1", port))
finally:
    sock.close()
sys.exit(0 if rc == 0 else 1)
PY
    return $?
  fi
  return 1
}

cc_connect_log_path() {
  local preferred="${CC_CONNECT_LOG_PATH:-/var/log/cc-connect.log}"
  local dir
  dir="$(dirname "${preferred}")"
  if mkdir -p "${dir}" >/dev/null 2>&1 && touch "${preferred}" >/dev/null 2>&1; then
    printf '%s' "${preferred}"
    return 0
  fi
  local fallback="${HOME:-/home/node}/.cc-connect/cc-connect.log"
  mkdir -p "$(dirname "${fallback}")" >/dev/null 2>&1 || true
  touch "${fallback}" >/dev/null 2>&1 || true
  printf '%s' "${fallback}"
}

cc_connect_is_running() {
  pgrep -x cc-connect >/dev/null 2>&1
}

cc_connect_start_service() {
  local cfg
  cfg="$(cc_connect_config_path)"
  if [[ ! -r "${cfg}" ]]; then
    echo "Config file not found or unreadable: ${cfg}" >&2
    return 1
  fi
  if ! have_cmd cc-connect; then
    echo "cc-connect command not found." >&2
    return 1
  fi
  if cc_connect_is_running; then
    echo "cc-connect is already running."
    return 0
  fi

  local log_path
  log_path="$(cc_connect_log_path)"
  local cc_port="${CC_CONNECT_PORT:-8080}"
  if port_is_listening "${cc_port}"; then
    echo "Port ${cc_port} is already in use. Please free it first." >&2
    return 1
  fi

  if [[ "$(id -u)" -eq 0 ]] && id node >/dev/null 2>&1; then
    if ! gosu node env CC_CONNECT_CFG="${cfg}" CC_CONNECT_LOG="${log_path}" bash -lc 'nohup cc-connect -config "${CC_CONNECT_CFG}" >>"${CC_CONNECT_LOG}" 2>&1 &'; then
      echo "Failed to start cc-connect as node user." >&2
      return 1
    fi
  else
    if ! env CC_CONNECT_CFG="${cfg}" CC_CONNECT_LOG="${log_path}" bash -lc 'nohup cc-connect -config "${CC_CONNECT_CFG}" >>"${CC_CONNECT_LOG}" 2>&1 &'; then
      echo "Failed to start cc-connect." >&2
      return 1
    fi
  fi

  sleep 2
  if cc_connect_is_running; then
    echo "cc-connect started successfully."
    echo "Log: ${log_path}"
    return 0
  fi

  echo "cc-connect failed to start. Recent logs:" >&2
  tail -n 20 "${log_path}" 2>/dev/null >&2 || true
  return 1
}

cc_connect_stop_service() {
  if ! cc_connect_is_running; then
    echo "cc-connect is not running."
    return 0
  fi
  pkill -x cc-connect >/dev/null 2>&1 || true
  sleep 2
  if cc_connect_is_running; then
    pkill -9 -x cc-connect >/dev/null 2>&1 || true
    sleep 1
  fi
  if cc_connect_is_running; then
    echo "Failed to stop cc-connect." >&2
    return 1
  fi
  echo "cc-connect stopped."
  return 0
}

read_required_input() {
  local prompt="$1"
  local secret="${2:-0}"
  local value=""
  while true; do
    if [[ "${secret}" == "1" ]]; then
      read -r -s -p "${prompt}" value
      echo >&2
    else
      read -r -p "${prompt}" value
    fi
    value="$(trim "${value}")"
    if [[ -n "${value}" ]]; then
      printf '%s' "${value}"
      return 0
    fi
    echo "Value cannot be empty." >&2
  done
}

select_claudecode_mode() {
  local mode_choice=""
  while true; do
    echo >&2
    echo "Select Claude Code mode:" >&2
    echo "1. default" >&2
    echo "2. acceptEdits" >&2
    echo "3. plan" >&2
    echo "4. bypassPermissions" >&2
    read -r -p "Select mode [1]: " mode_choice
    mode_choice="$(trim "${mode_choice}")"
    if [[ -z "${mode_choice}" ]]; then
      mode_choice="1"
    fi
    case "${mode_choice}" in
      1)
        printf '%s' "default"
        return 0
        ;;
      2)
        printf '%s' "acceptEdits"
        return 0
        ;;
      3)
        printf '%s' "plan"
        return 0
        ;;
      4)
        printf '%s' "bypassPermissions"
        return 0
        ;;
      *)
        echo "Invalid choice." >&2
        ;;
    esac
  done
}

select_codex_mode() {
  local mode_choice=""
  while true; do
    echo >&2
    echo "Select Codex mode:" >&2
    echo "1. suggest" >&2
    echo "2. auto-edit" >&2
    echo "3. full-auto" >&2
    echo "4. yolo" >&2
    read -r -p "Select mode [1]: " mode_choice
    mode_choice="$(trim "${mode_choice}")"
    if [[ -z "${mode_choice}" ]]; then
      mode_choice="1"
    fi
    case "${mode_choice}" in
      1)
        printf '%s' "suggest"
        return 0
        ;;
      2)
        printf '%s' "auto-edit"
        return 0
        ;;
      3)
        printf '%s' "full-auto"
        return 0
        ;;
      4)
        printf '%s' "yolo"
        return 0
        ;;
      *)
        echo "Invalid choice." >&2
        ;;
    esac
  done
}

append_cc_connect_project() {
  local cfg="$1"
  local project_name="$2"
  local agent_type="$3"
  local agent_mode="$4"
  local work_dir="$5"
  local platform_type="$6"
  local admin_from="$7"
  local allow_from="$8"
  local secret_a="$9"
  local secret_b="${10}"
  local guild_id="${11}"
  local thread_isolation="${12}"
  local enable_feishu_card="${13}"

  {
    echo
    echo "[[projects]]"
    echo "name = \"$(toml_escape "${project_name}")\""
    if [[ -n "${admin_from}" ]]; then
      echo "admin_from = \"$(toml_escape "${admin_from}")\""
    fi
    echo
    echo "[projects.agent]"
    echo "type = \"${agent_type}\""
    echo
    echo "[projects.agent.options]"
    echo "work_dir = \"$(toml_escape "${work_dir}")\""
    echo "mode = \"${agent_mode}\""
    echo
    echo "[[projects.platforms]]"
    echo "type = \"${platform_type}\""
    echo
    echo "[projects.platforms.options]"

    case "${platform_type}" in
      telegram)
        echo "token = \"$(toml_escape "${secret_a}")\""
        ;;
      discord)
        echo "token = \"$(toml_escape "${secret_a}")\""
        if [[ -n "${guild_id}" ]]; then
          echo "guild_id = \"$(toml_escape "${guild_id}")\""
        fi
        echo "thread_isolation = ${thread_isolation}"
        ;;
      feishu)
        echo "app_id = \"$(toml_escape "${secret_a}")\""
        echo "app_secret = \"$(toml_escape "${secret_b}")\""
        echo "enable_feishu_card = ${enable_feishu_card}"
        ;;
    esac

    if [[ -n "${allow_from}" ]]; then
      echo "allow_from = \"$(toml_escape "${allow_from}")\""
    fi
  } >>"${cfg}"
}

cc_validate_platform_credentials() {
  local cfg="$1"
  local line=""
  local clean=""
  local in_platform_block="0"
  local platform_type=""
  local has_token="0"
  local has_app_id="0"
  local has_app_secret="0"
  local checked_blocks=0
  local missing_blocks=0
  local tg_idx=0
  local dc_idx=0
  local fs_idx=0

  finalize_platform_block() {
    local label=""
    if [[ "${in_platform_block}" != "1" || -z "${platform_type}" ]]; then
      return 0
    fi

    case "${platform_type}" in
      telegram)
        tg_idx=$((tg_idx + 1))
        label="Credentials: telegram#${tg_idx}"
        checked_blocks=$((checked_blocks + 1))
        if [[ "${has_token}" == "1" ]]; then
          health_pass "${label}"
        else
          missing_blocks=$((missing_blocks + 1))
          health_fail "${label} missing token"
        fi
        ;;
      discord)
        dc_idx=$((dc_idx + 1))
        label="Credentials: discord#${dc_idx}"
        checked_blocks=$((checked_blocks + 1))
        if [[ "${has_token}" == "1" ]]; then
          health_pass "${label}"
        else
          missing_blocks=$((missing_blocks + 1))
          health_fail "${label} missing token"
        fi
        ;;
      feishu)
        fs_idx=$((fs_idx + 1))
        label="Credentials: feishu#${fs_idx}"
        checked_blocks=$((checked_blocks + 1))
        if [[ "${has_app_id}" == "1" && "${has_app_secret}" == "1" ]]; then
          health_pass "${label}"
        else
          missing_blocks=$((missing_blocks + 1))
          health_fail "${label} missing app_id/app_secret"
        fi
        ;;
    esac
  }

  while IFS= read -r line || [[ -n "${line}" ]]; do
    clean="${line%%#*}"
    clean="$(trim "${clean}")"
    if [[ -z "${clean}" ]]; then
      continue
    fi

    if [[ "${clean}" == "[[projects.platforms]]" || "${clean}" == "[[projects]]" ]]; then
      finalize_platform_block
      has_token="0"
      has_app_id="0"
      has_app_secret="0"
      platform_type=""
      if [[ "${clean}" == "[[projects.platforms]]" ]]; then
        in_platform_block="1"
      else
        in_platform_block="0"
      fi
      continue
    fi

    if [[ "${in_platform_block}" != "1" ]]; then
      continue
    fi

    if [[ "${clean}" =~ ^type[[:space:]]*=[[:space:]]*\"([A-Za-z0-9_-]+)\"$ ]]; then
      platform_type="${BASH_REMATCH[1]}"
      continue
    fi
    if [[ "${clean}" =~ ^token[[:space:]]*=[[:space:]]*\".+\"$ ]]; then
      has_token="1"
      continue
    fi
    if [[ "${clean}" =~ ^app_id[[:space:]]*=[[:space:]]*\".+\"$ ]]; then
      has_app_id="1"
      continue
    fi
    if [[ "${clean}" =~ ^app_secret[[:space:]]*=[[:space:]]*\".+\"$ ]]; then
      has_app_secret="1"
      continue
    fi
  done <"${cfg}"

  finalize_platform_block

  if [[ "${checked_blocks}" -eq 0 ]]; then
    health_fail "Credentials: no Telegram/Discord/Feishu platform block found"
    return 1
  fi
  if [[ "${missing_blocks}" -gt 0 ]]; then
    return 1
  fi
  return 0
}

npm_current_version() {
  local pkg="$1"
  if ! have_cmd npm; then
    return 0
  fi
  local raw
  raw="$(npm ls -g "${pkg}" --depth=0 --json 2>/dev/null || true)"
  printf '%s' "${raw}" | node -e '
let data = "";
process.stdin.on("data", (c) => data += c);
process.stdin.on("end", () => {
  try {
    const json = JSON.parse(data);
    const pkg = process.argv[1];
    const v = json?.dependencies?.[pkg]?.version || "";
    process.stdout.write(v);
  } catch {}
});
' "${pkg}"
}

npm_latest_version() {
  local pkg="$1"
  if ! have_cmd npm; then
    return 0
  fi
  npm view "${pkg}" version 2>/dev/null | tr -d '[:space:]'
}

cc_connect_current_version() {
  local out=""
  if have_cmd cc-connect; then
    out="$(cc-connect --version 2>/dev/null || true)"
    if [[ -z "${out}" ]]; then
      out="$(cc-connect --help 2>&1 | head -n 5 || true)"
    fi
  fi
  extract_semver "${out}"
}

cc_connect_latest_version() {
  if ! have_cmd git; then
    return 0
  fi
  git ls-remote --tags --refs https://github.com/chenhg5/cc-connect.git "refs/tags/v*" 2>/dev/null \
    | awk -F/ '{print $3}' \
    | sed 's/^v//' \
    | sort -V \
    | tail -n 1
}

detect_tool_versions() {
  local i
  for i in "${!TOOLS[@]}"; do
    IFS='|' read -r display key source <<<"${TOOLS[$i]}"
    local current=""
    local latest=""
    local status="unknown"
    local can_update="0"

    if [[ "${source}" == "npm" ]]; then
      current="$(normalize_semver "$(npm_current_version "${key}")")"
      latest="$(normalize_semver "$(npm_latest_version "${key}")")"
    else
      current="$(normalize_semver "$(cc_connect_current_version)")"
      latest="$(normalize_semver "$(cc_connect_latest_version)")"
    fi

    if [[ -n "${current}" && -n "${latest}" ]]; then
      if [[ "${current}" != "${latest}" ]]; then
        status="update"
        can_update="1"
      else
        status="latest"
      fi
    elif [[ -n "${current}" && -z "${latest}" ]]; then
      status="offline"
    elif [[ -z "${current}" && -n "${latest}" ]]; then
      status="unknown_current"
      can_update="1"
    else
      status="unknown"
    fi

    TOOL_CURRENT[$i]="${current}"
    TOOL_LATEST[$i]="${latest}"
    TOOL_STATUS[$i]="${status}"
    TOOL_CAN_UPDATE[$i]="${can_update}"
  done
}

tool_suffix() {
  local idx="$1"
  local status="${TOOL_STATUS[$idx]:-unknown}"
  case "${status}" in
    update)
      printf '%s' " (update available)"
      ;;
    latest)
      printf '%s' " (latest)"
      ;;
    offline)
      printf '%s' " (latest check unavailable)"
      ;;
    unknown_current)
      printf '%s' " (current unknown)"
      ;;
    *)
      printf '%s' ""
      ;;
  esac
}

print_tool_detail() {
  local idx="$1"
  local display source key
  IFS='|' read -r display key source <<<"${TOOLS[$idx]}"
  echo
  echo "Tool: ${display}"
  echo "Current: ${TOOL_CURRENT[$idx]:-unknown}"
  echo "Latest: ${TOOL_LATEST[$idx]:-unknown}"
}

update_npm_tool() {
  local pkg="$1"
  echo "Updating ${pkg}..."
  if npm install -g "${pkg}@latest"; then
    echo "Update completed: ${pkg}"
    return 0
  fi
  echo "Update failed for ${pkg}. Check permission and network." >&2
  return 1
}

update_cc_connect() {
  local latest_tag
  latest_tag="$(git ls-remote --tags --refs https://github.com/chenhg5/cc-connect.git "refs/tags/v*" 2>/dev/null | awk -F/ '{print $3}' | sort -V | tail -n 1 || true)"
  if [[ -z "${latest_tag}" ]]; then
    echo "Unable to get latest cc-connect tag." >&2
    return 1
  fi

  if ! have_cmd go; then
    echo "go is required to update cc-connect from source." >&2
    echo "Set INSTALL_GO_RUNTIME=true and recreate container, then retry." >&2
    return 1
  fi

  local tmpdir
  tmpdir="$(mktemp -d)"
  local outbin="${tmpdir}/cc-connect.new"

  echo "Building cc-connect from ${latest_tag}..."
  if ! git clone --depth 1 --branch "${latest_tag}" https://github.com/chenhg5/cc-connect.git "${tmpdir}/src" >/dev/null 2>&1; then
    rm -rf "${tmpdir}"
    echo "Failed to clone cc-connect source." >&2
    return 1
  fi

  (
    set -e
    cd "${tmpdir}/src"
    go build -ldflags='-w -s' -o "${outbin}" ./cmd/cc-connect || \
    go build -ldflags='-w -s' -o "${outbin}" . || \
    go build -ldflags='-w -s' -o "${outbin}" ./...
  ) >/dev/null 2>&1 || {
    rm -rf "${tmpdir}"
    echo "Failed to build cc-connect." >&2
    return 1
  }

  if [[ "$(id -u)" -eq 0 ]]; then
    install -m 0755 "${outbin}" /usr/local/bin/cc-connect
  elif have_cmd sudo; then
    sudo install -m 0755 "${outbin}" /usr/local/bin/cc-connect
  else
    rm -rf "${tmpdir}"
    echo "Need root privilege to install /usr/local/bin/cc-connect." >&2
    return 1
  fi

  rm -rf "${tmpdir}"
  echo "cc-connect updated to ${latest_tag}"
  return 0
}

update_tool_by_index() {
  local idx="$1"
  local display key source
  IFS='|' read -r display key source <<<"${TOOLS[$idx]}"

  if [[ "${TOOL_CAN_UPDATE[$idx]:-0}" != "1" ]]; then
    echo "No update available for ${display}."
    return 0
  fi

  if [[ "${source}" == "npm" ]]; then
    update_npm_tool "${key}"
  else
    update_cc_connect
  fi
}

menu_check_update() {
  while true; do
    detect_tool_versions
    echo
    echo "=== Check Updates ==="
    local i
    for i in "${!TOOLS[@]}"; do
      IFS='|' read -r display _ _ <<<"${TOOLS[$i]}"
      echo "$((i + 1)). ${display}$(tool_suffix "${i}")"
    done
    echo "0. Back"
    echo
    read -r -p "Select a tool: " choice

    if [[ "${choice}" == "0" ]]; then
      return 0
    fi
    if ! [[ "${choice}" =~ ^[1-5]$ ]]; then
      echo "Invalid choice."
      continue
    fi

    local idx=$((choice - 1))
    print_tool_detail "${idx}"
    if [[ "${TOOL_CAN_UPDATE[$idx]:-0}" == "1" ]]; then
      read -r -p "Update now? (y/N): " confirm
      if [[ "${confirm}" =~ ^[Yy]$ ]]; then
        update_tool_by_index "${idx}" || true
      fi
    else
      echo "No update action needed."
    fi
    pause
  done
}

menu_create_workspace() {
  local base_dir="${CLOUDCLI_DEFAULT_WORKSPACE_PATH:-${WORKSPACE_BASE_DEFAULT}}"
  echo
  echo "Workspace base: ${base_dir}"
  read -r -p "Enter workspace name (English only): " ws_name
  ws_name="$(trim "${ws_name}")"

  if [[ -z "${ws_name}" ]]; then
    echo "Workspace name cannot be empty."
    pause
    return 0
  fi

  if ! [[ "${ws_name}" =~ ^[A-Za-z][A-Za-z0-9_-]*$ ]]; then
    echo "Invalid name. Use English letters, numbers, _ or -; start with a letter."
    pause
    return 0
  fi

  if [[ ! -d "${base_dir}" ]]; then
    echo "Workspace base does not exist: ${base_dir}" >&2
    pause
    return 1
  fi

  local target="${base_dir}/${ws_name}"
  if [[ -e "${target}" ]]; then
    echo "Workspace already exists: ${target}"
    pause
    return 0
  fi

  if mkdir -p "${target}"; then
    if [[ "$(id -u)" -eq 0 ]] && id node >/dev/null 2>&1; then
      chown -R node:node "${target}" || true
    fi
    echo "Workspace created: ${target}"
  else
    echo "Failed to create workspace: ${target}" >&2
  fi
  pause
}

menu_health_status() {
  HC_PASS=0
  HC_FAIL=0
  HC_SKIP=0

  echo
  echo "=== Health Status ==="

  health_check "pid1 process exists" "ps -p 1 >/dev/null"
  health_check "cron process" "pgrep -x cron >/dev/null"

  if have_cmd tailscaled; then
    if [[ -e /dev/net/tun ]]; then
      health_check "tailscaled process" "pgrep -x tailscaled >/dev/null"
    else
      health_skip "tailscaled process (/dev/net/tun missing)"
    fi
  else
    health_skip "tailscaled process (tailscaled not installed)"
  fi

  local cloudcli_enable_lc
  cloudcli_enable_lc="$(printf '%s' "${CLOUDCLI_ENABLE:-true}" | tr '[:upper:]' '[:lower:]')"
  local cloudcli_port="${CLOUDCLI_PORT:-3001}"

  if [[ "${cloudcli_enable_lc}" == "false" || "${cloudcli_enable_lc}" == "0" || "${cloudcli_enable_lc}" == "no" || "${cloudcli_enable_lc}" == "off" ]]; then
    health_skip "cloudcli checks (CLOUDCLI_ENABLE=${CLOUDCLI_ENABLE:-false})"
  else
    health_check "cloudcli CLI" "cloudcli version >/dev/null 2>&1"
    health_check "cloudcli listening" "if command -v ss >/dev/null 2>&1; then ss -ltn 2>/dev/null | awk '{print \$4}' | grep -Eq '[:.]${cloudcli_port}\$'; elif command -v netstat >/dev/null 2>&1; then netstat -ltn 2>/dev/null | awk '{print \$4}' | grep -Eq '[:.]${cloudcli_port}\$'; elif command -v python3 >/dev/null 2>&1; then python3 -c 'import socket,sys; s=socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.settimeout(0.5); rc=s.connect_ex((\"127.0.0.1\", int(sys.argv[1]))); s.close(); raise SystemExit(0 if rc == 0 else 1)' '${cloudcli_port}'; else false; fi"
    health_check "cloudcli HTTP" "curl -fsS 'http://127.0.0.1:${cloudcli_port}/' >/dev/null"
  fi

  echo "Summary: pass=${HC_PASS} fail=${HC_FAIL} skip=${HC_SKIP}"
  pause
}

menu_cc_connect_quick_bind() {
  local cfg
  cfg="$(cc_connect_config_path)"

  if ! ensure_cc_connect_config "${cfg}"; then
    echo "Unable to prepare cc-connect config: ${cfg}" >&2
    pause
    return 1
  fi

  echo
  echo "=== cc-connect quick bind ==="
  echo "Config file: ${cfg}"

  local project_name=""
  while true; do
    read -r -p "Project name (English only): " project_name
    project_name="$(trim "${project_name}")"
    if [[ -z "${project_name}" ]]; then
      echo "Project name cannot be empty."
      continue
    fi
    if ! [[ "${project_name}" =~ ^[A-Za-z][A-Za-z0-9_-]*$ ]]; then
      echo "Invalid name. Use English letters, numbers, _ or -; start with a letter."
      continue
    fi
    if cc_project_exists "${cfg}" "${project_name}"; then
      echo "Project already exists in cc-connect config: ${project_name}"
      pause
      return 0
    fi
    break
  done

  local agent_type=""
  local agent_choice=""
  while true; do
    echo
    echo "Agent type:"
    echo "1. claudecode"
    echo "2. codex"
    read -r -p "Select agent [1]: " agent_choice
    agent_choice="$(trim "${agent_choice}")"
    if [[ -z "${agent_choice}" ]]; then
      agent_choice="1"
    fi
    case "${agent_choice}" in
      1)
        agent_type="claudecode"
        break
        ;;
      2)
        agent_type="codex"
        break
        ;;
      *)
        echo "Invalid choice."
        ;;
    esac
  done

  local agent_mode=""
  if [[ "${agent_type}" == "claudecode" ]]; then
    agent_mode="$(select_claudecode_mode)"
  else
    agent_mode="$(select_codex_mode)"
  fi

  local workspace_root="${CLOUDCLI_DEFAULT_WORKSPACE_PATH:-${WORKSPACE_BASE_DEFAULT}}"
  local default_work_dir="${workspace_root}/${project_name}"
  local work_dir=""
  while true; do
    read -r -p "Project directory [${default_work_dir}]: " work_dir
    work_dir="$(trim "${work_dir}")"
    if [[ -z "${work_dir}" ]]; then
      work_dir="${default_work_dir}"
    fi
    if [[ "${work_dir}" != /* ]]; then
      echo "Please use an absolute path."
      continue
    fi
    break
  done

  if [[ ! -d "${work_dir}" ]]; then
    if prompt_yes_no "Directory not found. Create it now? (Y/n):" "Y"; then
      if ! mkdir -p "${work_dir}"; then
        echo "Failed to create directory: ${work_dir}" >&2
        pause
        return 1
      fi
      if [[ "$(id -u)" -eq 0 ]] && id node >/dev/null 2>&1; then
        chown -R node:node "${work_dir}" || true
      fi
    else
      echo "Cancelled: directory must exist for binding."
      pause
      return 0
    fi
  fi

  local admin_from=""
  read -r -p "Admin users (optional, comma IDs; * = all): " admin_from
  admin_from="$(trim "${admin_from}")"

  local platform_type=""
  local platform_choice=""
  while true; do
    echo
    echo "Chat channel:"
    echo "1. Telegram"
    echo "2. Discord"
    echo "3. Feishu"
    read -r -p "Select channel: " platform_choice
    platform_choice="$(trim "${platform_choice}")"
    case "${platform_choice}" in
      1)
        platform_type="telegram"
        break
        ;;
      2)
        platform_type="discord"
        break
        ;;
      3)
        platform_type="feishu"
        break
        ;;
      *)
        echo "Invalid choice."
        ;;
    esac
  done

  local allow_from=""
  local secret_a=""
  local secret_b=""
  local guild_id=""
  local thread_isolation="false"
  local enable_feishu_card="true"

  case "${platform_type}" in
    telegram)
      secret_a="$(read_required_input "Telegram bot token: " 1)"
      read -r -p "Allow users (optional, comma IDs; default *): " allow_from
      allow_from="$(trim "${allow_from}")"
      if [[ -z "${allow_from}" ]]; then
        allow_from="*"
      fi
      ;;
    discord)
      secret_a="$(read_required_input "Discord bot token: " 1)"
      read -r -p "Discord guild_id (optional, recommend for slash command): " guild_id
      guild_id="$(trim "${guild_id}")"
      read -r -p "Allow users (optional, comma IDs; default *): " allow_from
      allow_from="$(trim "${allow_from}")"
      if [[ -z "${allow_from}" ]]; then
        allow_from="*"
      fi
      if prompt_yes_no "Enable thread isolation? (y/N):" "N"; then
        thread_isolation="true"
      fi
      ;;
    feishu)
      secret_a="$(read_required_input "Feishu app_id: " 0)"
      secret_b="$(read_required_input "Feishu app_secret: " 1)"
      read -r -p "Allow users (optional open_id list; default *): " allow_from
      allow_from="$(trim "${allow_from}")"
      if [[ -z "${allow_from}" ]]; then
        allow_from="*"
      fi
      if prompt_yes_no "Enable Feishu card replies? (Y/n):" "Y"; then
        enable_feishu_card="true"
      else
        enable_feishu_card="false"
      fi
      ;;
  esac

  echo
  echo "=== Confirm cc-connect binding ==="
  echo "Project: ${project_name}"
  echo "Agent: ${agent_type} (mode=${agent_mode})"
  echo "Work dir: ${work_dir}"
  echo "Platform: ${platform_type}"
  if [[ -n "${admin_from}" ]]; then
    echo "Admin users: ${admin_from}"
  else
    echo "Admin users: (not set)"
  fi
  echo "Allow users: ${allow_from}"
  echo "Config file: ${cfg}"

  if ! prompt_yes_no "Write this project into config.toml? (Y/n):" "Y"; then
    echo "Cancelled."
    pause
    return 0
  fi

  if ! append_cc_connect_project \
    "${cfg}" \
    "${project_name}" \
    "${agent_type}" \
    "${agent_mode}" \
    "${work_dir}" \
    "${platform_type}" \
    "${admin_from}" \
    "${allow_from}" \
    "${secret_a}" \
    "${secret_b}" \
    "${guild_id}" \
    "${thread_isolation}" \
    "${enable_feishu_card}"; then
    echo "Failed to update config file: ${cfg}" >&2
    pause
    return 1
  fi

  echo "Project binding added to: ${cfg}"
  echo "Next step: run 'cc-connect -config ${cfg}' to start."
  pause
}

menu_cc_connect_self_check() {
  HC_PASS=0
  HC_FAIL=0
  HC_SKIP=0

  local cfg
  cfg="$(cc_connect_config_path)"

  echo
  echo "=== cc-connect connection self-check ==="
  echo "Config file: ${cfg}"

  if [[ -f "${cfg}" ]]; then
    health_pass "config file exists"
  else
    health_fail "config file not found"
  fi
  if [[ -r "${cfg}" ]]; then
    health_pass "config file readable"
  else
    health_fail "config file not readable"
  fi

  if [[ -r "${cfg}" ]]; then
    local project_count
    project_count="$(grep -Ec '^[[:space:]]*\[\[projects\]\][[:space:]]*$' "${cfg}" || true)"
    if [[ "${project_count}" -gt 0 ]]; then
      health_pass "project blocks: ${project_count}"
    else
      health_fail "project blocks: 0"
    fi

    local workdir_count
    workdir_count="$(grep -Ec '^[[:space:]]*work_dir[[:space:]]*=' "${cfg}" || true)"
    if [[ "${workdir_count}" -gt 0 ]]; then
      health_pass "work_dir entries: ${workdir_count}"
    else
      health_fail "work_dir entries: 0"
    fi

    local wd
    while IFS= read -r wd; do
      wd="$(trim "${wd}")"
      if [[ -z "${wd}" ]]; then
        continue
      fi
      if [[ -d "${wd}" ]]; then
        health_pass "work_dir exists: ${wd}"
      else
        health_fail "work_dir missing: ${wd}"
      fi
    done < <(sed -n 's/^[[:space:]]*work_dir[[:space:]]*=[[:space:]]*"\(.*\)"[[:space:]]*$/\1/p' "${cfg}")

    cc_validate_platform_credentials "${cfg}" || true
  else
    health_skip "skip credentials/work_dir checks (config unreadable)"
  fi

  if have_cmd cc-connect; then
    health_check "cc-connect CLI" "cc-connect --version >/dev/null 2>&1"
  else
    health_fail "cc-connect CLI not found"
  fi

  local cc_process_up="0"
  if pgrep -x cc-connect >/dev/null 2>&1; then
    cc_process_up="1"
    health_pass "cc-connect process"
  else
    health_fail "cc-connect process"
  fi

  local cc_port="${CC_CONNECT_PORT:-8080}"
  local cc_port_up="0"
  if port_is_listening "${cc_port}"; then
    cc_port_up="1"
  fi

  if [[ "${cc_process_up}" == "1" && "${cc_port_up}" == "1" ]]; then
    health_pass "cc-connect listening on :${cc_port}"
  elif [[ "${cc_process_up}" == "1" && "${cc_port_up}" == "0" ]]; then
    health_fail "cc-connect listening on :${cc_port} (process up but port not open)"
  elif [[ "${cc_process_up}" == "0" && "${cc_port_up}" == "1" ]]; then
    health_fail "cc-connect listening on :${cc_port} (port occupied by another process)"
  else
    health_skip "cc-connect listening on :${cc_port} (service not running)"
  fi

  echo "Summary: pass=${HC_PASS} fail=${HC_FAIL} skip=${HC_SKIP}"
  pause
}

menu_cc_connect_service_control() {
  while true; do
    local cfg
    cfg="$(cc_connect_config_path)"
    local cc_port="${CC_CONNECT_PORT:-8080}"
    local log_path
    log_path="$(cc_connect_log_path)"

    echo
    echo "=== cc-connect service control ==="
    echo "Config: ${cfg}"
    echo "Port: ${cc_port}"
    echo "Log: ${log_path}"
    if cc_connect_is_running; then
      echo "Status: running"
    else
      echo "Status: stopped"
    fi
    echo "1. Start service"
    echo "2. Stop service"
    echo "3. Restart service"
    echo "4. Show recent logs"
    echo "0. Back"
    echo
    read -r -p "Select an option: " action

    case "${action}" in
      1)
        cc_connect_start_service || true
        pause
        ;;
      2)
        cc_connect_stop_service || true
        pause
        ;;
      3)
        cc_connect_stop_service || true
        cc_connect_start_service || true
        pause
        ;;
      4)
        if [[ -r "${log_path}" ]]; then
          echo "--- tail -n 80 ${log_path} ---"
          tail -n 80 "${log_path}" || true
        else
          echo "Log file not readable: ${log_path}"
        fi
        pause
        ;;
      0)
        return 0
        ;;
      *)
        echo "Invalid choice."
        ;;
    esac
  done
}

menu_main() {
  while true; do
    echo
    echo "=== Coding Agent Config ==="
    echo "1. Quick configure provider (ccman)"
    echo "2. Check updates"
    echo "3. Add workspace"
    echo "4. Health status"
    echo "5. cc-connect quick bind"
    echo "6. cc-connect connection self-check"
    echo "7. cc-connect service control"
    echo "0. Exit"
    echo
    read -r -p "Select an option: " choice

    case "${choice}" in
      1)
        if have_cmd ccman; then
          ccman
        else
          echo "ccman not found."
          pause
        fi
        ;;
      2)
        menu_check_update
        ;;
      3)
        menu_create_workspace
        ;;
      4)
        menu_health_status
        ;;
      5)
        menu_cc_connect_quick_bind
        ;;
      6)
        menu_cc_connect_self_check
        ;;
      7)
        menu_cc_connect_service_control
        ;;
      0)
        exit 0
        ;;
      *)
        echo "Invalid choice."
        ;;
    esac
  done
}

menu_main
